source 'http://rubygems.org'

gem 'rails', '3.0.7'
gem 'acts-as-taggable-on'
gem 'awesome_print', :require => 'ap'
gem 'couchrest'
gem 'delayed_job'
gem 'devise'
gem 'domainatrix'
gem 'gchartrb'
gem 'google-search'
gem 'hashie'
gem 'jquery-rails'
gem 'json'
gem 'nifty-generators'
gem 'omniauth'
gem 'rails3-generators'
gem 'sqlite3'
gem 'twitter'
gem 'twitter-text'
gem 'will_paginate', "~> 3.0.pre2"
gem 'yajl-ruby'
gem 'gchartrb'
gem 'sunspot_rails', '~> 1.2.1'
gem 'compete'

group :test do
  gem 'factory_girl_rails', '1.1.beta1'
  gem 'mocha'
  gem 'rspec-rails'
  gem 'ZenTest'
  gem 'simplecov'
  gem 'webmock'
  gem 'yard'
end
