source 'http://rubygems.org'

gem 'rails', '3.0.9'
gem 'acts-as-taggable-on'
gem 'awesome_print', :require => 'ap'
gem 'bson_ext'
gem 'couchrest'
gem 'delayed_job'
gem 'devise'
gem 'domainatrix'
gem 'feedzirra'
gem 'gchartrb'
gem 'google-search'
gem 'hashie'
gem 'jquery-rails'
gem 'json'
gem 'nifty-generators'
gem 'omniauth', '~> 0.2.4'
gem 'rails3-generators'
gem 'sqlite3'
gem 'twitter'

gem 'will_paginate', "~> 3.0.pre2"
gem 'yajl-ruby'
gem 'gchartrb'
gem 'sunspot_rails', '~> 1.2.1'
gem 'compete'
gem 'mongo_mapper'

group :test do
  gem 'factory_girl_rails', '1.1.beta1'
  gem 'mocha'
  gem 'rspec-rails'
  gem 'ZenTest'
  gem 'simplecov'
  gem 'webmock'
  gem 'yard'
  gem 'spork', '~> 0.9.0.rc'
end
